### ISSUE TITLE
Getting error message that I've been trying to debug since 4pm yesterday.

### ISSUE THREAD

**Issue by jenniferabowd** [jenkaplan/underTen#2]
CONTEXT

WHAT USER STORY YOU ARE WORKING ON:
Emeka created the meals database and I have created the auth. We have merged the two, but now we are working on debugging it. Once this is fully debugged we will have a completed base app.

BUG/ERROR:

<img width="484" alt="screen shot 2017-02-06 at 9 29 47 am" src="https://cloud.githubusercontent.com/assets/23088445/22650921/1d0eb136-ec4f-11e6-982a-303db8fdc78f.png">

WHAT I'VE TRIED
I got this error at 4pm yesterday. I've been trying to debug it on and off since then. I asked Anthony if he can help, but he couldn't figure it out. I am at a loss for what this error is.

QUESTION
Can you help me debug this error?

@thoughtbyte @parisyee

**Comment by vabruzzo** [comment]
what branch are you working on where i can see the code that generates this error? form the looks of it, your using a middleware without requiring it or your syntax for using middleware is wrong.

**Comment by jenniferabowd** [comment]
Hi Vince, 

I am working on create-auth. Emeka and I merged our branches yesterday.

Best,

Jen

**Comment by vabruzzo** [comment]
compare the meals and auth routes files. one of them is missing something
